In [18]:
import numpy as np



print numpy version

In [19]:
print (np.version)

<module 'numpy.version' from '/home/abubakar/miniconda3/envs/datascience/lib/python3.8/site-packages/numpy/version.py'>


create a null vector of size 10

In [20]:
null_vector = np.zeros(10)
print (null_vector)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


to find the memory size of an array, you use the .nbytes function

you get the documentation of Numpy add function through the command line by entering "pydoc numpy.add" in your command

In [21]:
#create a vector of null values but the 5th value is 1
null_vectors2= np.zeros(10)
null_vectors2[4]= 1
print (null_vectors2)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [22]:
#create a vector with values ranging from 10-49
vectors= np.arange (10,50)
print (vectors)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [23]:
#reverse the vector
reversed_vector = vectors[::-1]
print (reversed_vector)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [24]:
#create a 3x3 matrix 0-8
matrix= np.arange(9).reshape(3,3)
print (matrix)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [25]:
#FIND THE INDICES OF NON-ZERO ELEMENTS
arr=np.array ([1,2,0,0,4,0])
none_zero = np.nonzero(arr)
print (none_zero)


(array([0, 1, 4]),)


In [26]:
#CREATE A 3x3 IDENTITY MATRIX
identity_matrix = np.eye(3)
print (identity_matrix)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [27]:
#CREATE A 3x3x3 ARRAY WITH RANDOM VALUES
random_array = np.random.rand (3,3,3)
print (random_array)


[[[0.75581801 0.59973656 0.31371905]
  [0.05745786 0.77431578 0.6706081 ]
  [0.72712788 0.76957892 0.32356034]]

 [[0.61824554 0.21399238 0.89500313]
  [0.35554435 0.61368434 0.59054006]
  [0.62829238 0.2769666  0.21367658]]

 [[0.40405428 0.16890282 0.96471999]
  [0.0481835  0.00143246 0.85068874]
  [0.87504658 0.92220062 0.35786008]]]


In [28]:
#CREATE 10x10 ARRAY WITH RANDOM VALUES. FIND THE MINIMUM AND MAXIMUM VALUES
ten_array = np.random.rand(10,10)
print (ten_array)
print ('The minimum value is', np.min(ten_array))
print ("The maximum value is", np.max(ten_array))



[[0.79784052 0.56616236 0.26323964 0.72773104 0.73755223 0.85689894
  0.10530323 0.67804321 0.53288065 0.9454367 ]
 [0.44548439 0.44175343 0.09160609 0.59299797 0.49289413 0.22019427
  0.3855878  0.9569387  0.46878381 0.62657559]
 [0.88008182 0.18582432 0.90839675 0.38401473 0.29885357 0.11308402
  0.04117649 0.95453378 0.2110944  0.01197106]
 [0.33390419 0.59479316 0.88324929 0.87307097 0.900821   0.00579348
  0.14515648 0.29278718 0.36083946 0.29878546]
 [0.51211624 0.82672982 0.96663082 0.48300077 0.65326758 0.22141907
  0.00263438 0.19042504 0.37277301 0.74101714]
 [0.82754856 0.80182089 0.23494626 0.87111661 0.97236494 0.40292393
  0.02788478 0.85672029 0.69837165 0.18081043]
 [0.01528629 0.48927997 0.52384505 0.18226186 0.13429817 0.83174489
  0.50889441 0.27952711 0.42502956 0.31118589]
 [0.52352978 0.30064648 0.23346619 0.72383424 0.38007656 0.86536029
  0.20256968 0.45204942 0.39833609 0.66329771]
 [0.45646937 0.32977811 0.35476638 0.56043108 0.1005545  0.14337383
  0.78551527

In [29]:
#Create a random vector of size 30and find the mean
size_30 = np.random.rand (30)
print (size_30)
print ("The mean of the random vector is", np.mean(size_30))


[0.38394993 0.1683083  0.2554773  0.89135618 0.41019508 0.21710691
 0.57803786 0.40323954 0.92688498 0.66767644 0.24070957 0.53644881
 0.05871048 0.18078052 0.72395637 0.3599133  0.98803019 0.31549662
 0.44083813 0.91497639 0.64339015 0.32033324 0.531632   0.97329898
 0.83854049 0.51984917 0.68714571 0.23589533 0.6347051  0.14691576]
The mean of the random vector is 0.5064599612991458


In [30]:

rows = 5
cols = 5

# Create a matrix of zeros
array = np.zeros((rows, cols))

# Set the border elements to 1
array[0, :] = 1  # top row
array[-1, :] = 1  # bottom row
array[:, 0] = 1  # leftmost column
array[:, -1] = 1  # rightmost column
print(array)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


To add a border filled with zeros around an existing array, one has to first create the array, then use the indexing numbers round the array (top row, bottom row, leftmost and rightmost columns)


In [ ]:
#CREATE A 5x5 MATRIX WITH VALUES 1234 BELOW THE DIAGONAL
MATRIX= np.zeros((5,5))
np.fill_diagonal(MATRIX[1:].[1,2,3,4])
print (MATRIX)

In [ ]:
#Create 8x8 matrix and fill it with checkerboard pattern
matrix = np.zeros((8, 8), dtype=int)

# Fill the checkerboard pattern
matrix[1::2, ::2] = 1  # Odd rows, even columns
matrix[::2, 1::2] = 1  # Even rows, odd columns

print(matrix)